# 应用名称
spring:
  application:
    name: seckill

  # 应用服务 WEB 访问端口
  server:
    port: 8080

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: false

  #静态资源处理
  resources:
    #启用默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源链中启用缓存，默认启用
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析,默认禁用
      compressed: true
      #启用H5应用缓存，默认禁用
      html-application-cache: true
    #静态资源位置
    static-locations: classpath:/static/

  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://182.254.171.122:3306/seckill?serverTimezone=Asia/Shanghai
    # 数据库用户名&密码：
    username: root
    password: yuerer0591@fjlt
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数，默认为10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0 表示永久存活， 默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
#    host: 139.224.43.179
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
#    password: szxc@0591
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5

  rabbitmq:
    addresses:
      #服务器地址
      host: 127.0.0.1
      #用户名
      username: guest
      #密码
      password: guest
      #虚拟主机
      virtual-host: /
      #端口
      port: 5672
      listener:
        simple:
          #消费者最小数量
          concurrency: 10
          #消费者最大数量
          max-concurrency: 10
          #限制消费者每次只处理一条消息，处理完再继续下一条消息
          prefetch: 1
          #启动时是否默认启动容器，默认true
          auto-startup: true
          #被拒绝时重新进入队列
          default-requeue-rejected: true
      template:
        retry:
          #发布重试，默认false
          enabled: true
          #重试时间 默认1000ms
          initial-interval: 1000
          #重试最大次数，默认3次
          max-attempts: 3
          #重试最大间隔时间，默认10000ms
          max-interval: 10000
          #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
          multiplier: 1.0

# mybatis-plus配置
mybatis-plus:
  # 配置Mapper配置文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: cn.yubajin.seckill.pojo
logging:
  level:
    cn.yubajin.seckill.mapper: debug
